### ISSUE TITLE
Unexpected behavior in saving network as :float()

### ISSUE THREAD

**Issue by mbchang** [torch/nngraph#121] opened 2016-07-07 06:42 UTC
Please see the issue posted in https://github.com/torch/torch7/issues/711. I had accidentally submitted an issue for torch/nngraph there, and I'm not sure how to remove it. Thank you!

**Comment by soumith** [comment] 2016-07-07 10:17
before loading the model, just execute the line:
require 'cunn'

**Comment by mbchang** [comment] 2016-07-07 15:25
@soumith I do realize that executing ```require cunn``` lets me load the checkpoint, if my computer already has gpu capabilites. However, I intend to load the checkpoint on a computer that does not have gpu capabilities, for which I can't install cunn in the first place.

**Comment by fmassa** [comment] 2016-07-25 21:35
@soumith There is indeed a problem here.
I think the guilty guy [is in this line](https://github.com/torch/nngraph/blob/master/gmodule.lua#L307). When we call `type`, the buffers are all cleared, but the references of the old forward inputs are still there. The same might apply for the backward nodes.

Two workarounds for the moment: after converting to `float` and before saving, either do
* `:clearState()`, or
* run a forward/backward pass using `float` data.

I think this should be addressed in `nngraph` though.

**Comment by soumith** [comment] 2016-07-27 05:19
@fmassa I dont think that holds for `type`. What you are saying actually might be affecting `clearState` though.
To check what you said, I added this assertion to tests, and it passes.
https://github.com/torch/nngraph/commit/08d0b5db1b56bbb52dfb81a233d288d3654c07d8

**Comment by soumith** [comment] 2016-07-27 05:22
@mbchang reproduced your issue. I am looking into it.

**Comment by mbchang** [comment] 2016-07-27 05:24
Thanks @soumith, that would be a great help!

**Comment by fmassa** [comment] 2016-07-27 05:27
@soumith tests passes because forward is runned after model conversion. Without the forward it will fail I think.
but my workaround didn't work for networks containing cudnn modules which were converted to nn, I had to recreate the module and copy the parameters by hand

**Comment by soumith** [comment] 2016-07-27 05:29
oohh i see, ok makes sense. looking into it.

**Comment by fmassa** [comment] 2016-07-27 05:36
I just realized that the line that my comment was pointing is off. I was referring to [this line](https://github.com/torch/nngraph/blob/master/gmodule.lua#L313), which I'll copy here to avoid other ambiguities:
```lua
child.data.input[mapindex] = x
```

**Comment by soumith** [comment] 2016-07-27 05:45
@mbchang @fmassa fixed it via #126 . Reinstall nngraph and it should be fixed.

**Closed** 2016-07-27 05:45 UTC
